### ISSUE TITLE
Missing classes

### ISSUE THREAD

**Issue by AlexMooney** [hopshackle/ArsMagica#1]
This repository seems to be missing a number of classes.  I can't find `World`, `Organisation`, `Agent`, `Location` and so on and so forth.  Any chance of posting a link to a binary?

**Comment by hopshackle** [comment]
Hi Alex,

The Ars Magica project is written on top of my Simulation project, which
provides some of the plumbing - including World, Agent etc. You can find
all the relevant code in the 'Simulation' repository on GitHub (also under
my id).

Feel free to ping me any questions at james@janigo.co.uk

Cheers,

James

**Comment by AlexMooney** [comment]
Now I'm missing the `GeneticProperties.txt` (but I think default settings are being applied) as well as a bunch of files from `C:\Simulations`, such as `CovenantNames.txt`, `StartingMagi.txt`, and `MagusNames.txt`.  I made my own covenant names file, then noticed there were ~25 other `.java` files which reference `C:\\Simulations`.

**Comment by hopshackle** [comment]
Good point - I forgot to include the config files in the repository. I've now added them to the Ars Magica project, along with a setup.txt file that may provide some useful pointers.

There is also a snapshot set of some example output from a run (plus a few other comments from me on the format) in the Ars Magica forums at http://forum.atlas-games.com/viewtopic.php?f=4&t=30686 that might be useful. 

Shout if you have any other questions.

**Comment by AlexMooney** [comment]
Looks like you're working on this again!  It would be awesome if you could add an example output to the repo, so that it could be looked over without getting it running independently.  😄

**Comment by hopshackle** [comment]
I'll see what I can do 😎

**Comment by hopshackle** [comment]
OK - Done. I've updated the ReadMe on the repository - let me know if there are any access issues.

**Comment by AlexMooney** [comment]
Access works fine.  Thanks so much for putting together the samples!
